apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: nginx
spec:
 schedule: "*/1 * * * *"
 jobTemplate:
  spec:
   template:
    spec:
     containers:
     - name: nginx
       image: nginx:1.9.1
       imagePullPolicy: IfNotPresent
       args: 
       - /bin/sh
       - -c
       - date; echo Hello
     restartPolicy: OnFailure
