apiVersion: apps/v1
kind: Deployment
metadata:
 name: test-deploy
spec:
 replicas: 3
 selector:
  matchLabels:
   apps: test
 template:
  metadata:
   labels:
    app: test
  spec:
   containers:
   - name: nginx
     image: nginx:alpine
