apiVersion: v1
kind: Pod
metadata:
 name: myPod
 namespace: default
 labels:
  app: test
  env: test-env
 annotations:
    build: demo
spec:
 containers:
 - name: nginx-test
   image: nginx:alpine
   ports:
   - containerPort: 80
 - name: redis-test
   image: redis
 
